### ISSUE TITLE
Newbie-ish question

### ISSUE THREAD

**Issue by ChrisRG711** [shbatm/MMM-Carousel#74] opened 2023-10-03 16:29 UTC
I see the samples showing the carousel config. In the slides specific examples it shows just list the names of the modules. Does the rest of the config.js still contain the full list and config of each module or is that done differently? anyone have a config.js they can black out sensitive parts and share?

Thank you in advance. I appreciate the help

**Comment by KristjanESPERANTO** [comment] 2023-10-07 14:10
Here is a basic `config.js`. Is that helping?

```js
// MagicMirror² config file
let config = {
  address: "localhost",
  port: 8080,
  basePath: "/",
  ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"],
  modules: [
    {
      module: "clock",
      position: "top_left"
    },
    {
      module: "alert"
    },
    {
      module: "updatenotification",
      position: "top_bar"
    },
    {
      module: "newsfeed",
      position: "top_left",
      config: {
        feeds: [
          {
            title: "tagesschau.de",
            url: "https://www.tagesschau.de/xml/rss2/"
          }
        ]
      }
    },
    {
      module: "weather",
      position: "top_right",
      header: "Wetter in ***",
      config: {
        appendLocationNameToHeader: false,
        decimalSymbol: ",",
        weatherProvider: "openweathermap",
        type: "forecast",
        location: "***",
        locationID: "***",
        maxNumberOfDays: 8,
        apiKey: "***",
        carouselId: 1
      }
    },
    {
      module: "weather",
      position: "top_right",
      config: {
        appendLocationNameToHeader: false,
        decimalSymbol: ",",
        weatherProvider: "openweathermap",
        type: "current",
        location: "***",
        locationID: "***",
        maxNumberOfDays: 8,
        apiKey: "***",
        showWindDirection: false,
        carouselId: 99
      }
    },
    {
      module: "MMM-Carousel",
      position: "bottom_bar",
      config: {
        transitionInterval: 12000,
        showPageIndicators: true,
        showPageControls: false,
        ignoreModules: ["updatenotification", "alert", "compliments", "clock"],
        mode: "slides",
        slides: {
          "Slide  1": [{ name: "weather", carouselId: 1 }],
          "Slide  2": [{ name: "weather", carouselId: 99 }, { name: "newsfeed" }],
        },
        keyBindings: {
          enabled: true,
          mode: "DEFAULT",
          map: {
            NextSlide: "ArrowRight",
            PrevSlide: "ArrowLeft",
            Slide0: "ArrowUp",
            Pause: "ArrowDown"
          }
        }
      }
    },
    {
      module: "MMM-KeyBindings",
      config: {
        enableKeyboard: true,
        evdev: { enabled: false }
      }
    }
  ]
};

/** ************* DO NOT EDIT THE LINE BELOW */
if (typeof module !== "undefined") {
  module.exports = config;
}
```

**Comment by KristjanESPERANTO** [comment] 2023-11-01 22:50
@ChrisRG711 Do you still have this issue?

**Comment by ChrisRG711** [comment] 2023-11-22 13:03
No that helped. I do have a question about the module. In all the examples it shows slides: { 
but that never works for me. I have to use slides: [

**Comment by KristjanESPERANTO** [comment] 2023-11-22 13:29
> I have to use slides: [

That was the case with the [old module from barnabycolby](https://github.com/barnabycolby/MMM-Carousel).

What do you get when you enter `git remote -v` in the terminal when you are in the directoy of this module?

It should return the url `https://github.com/shbatm/MMM-Carousel` like this:

```sh
kristjan@debian:~/MagicMirror/modules/MMM-Carousel$ git remote -v
origin	https://github.com/shbatm/MMM-Carousel (fetch)
origin	https://github.com/shbatm/MMM-Carousel (push)
```

**Comment by ChrisRG711** [comment] 2023-11-22 15:05
that is what i got. But as per normal. Its working now with the [] the only issue is that its not respecting the slides. I have the following as config. I have not had any other problems this has been working AWESOME. I love the module. I just keep trying to get the right mods on the right slides etc.  But now it does not do separate slides. It puts slides 1 and 2 on the same slide and stays there. I am sure its something dumb and small i did, Sorry about that. you have been very helpful
{
            module: 'MMM-Carousel',
            config: {
                transitionInterval: 10000,
		position: "bottom_bar",
                ignoreModules: ['alert'],
                mode: 'slides',
                slides: [
	 ["clock","MMM-SpaceLaunchNow",'MMM-WiFiPassword','internet-monitor',"MMM-RAIN-MAP",'MMM-NASA'],
         ['UpcomingBirthdays','MMM-WiFiPassword']
               ]
       }
},

**Comment by KristjanESPERANTO** [comment] 2023-11-22 17:12
The problem is that you placed the position inside the config, but it has to be outside. Try this simple config:

```js
		{
			module: "MMM-Carousel",
			position: "bottom_bar",
			config: {
				transitionInterval: 10000,
				ignoreModules: ["alert"],
				mode: "slides",
				slides: [
					["clock", "weather"],
					["compliments"]
				]
			}
		},
```

**Comment by KristjanESPERANTO** [comment] 2023-11-22 21:53
You're welcome :slightly_smiling_face:

Please close this issue if your problems are solved.

And have fun with your mirror! :mirror: :smiley:

**Closed** 2023-11-23 12:54 UTC
